FROM python:3.12.0-alpine3.18

LABEL maintainer="cloud-optimisation-and-accountability <CloudOptimisationandAccountabilityTeam@justice.gov.uk>"

# Install system dependencies
RUN apk add --no-cache --no-progress \
  libffi-dev \
  build-base \
  curl \
  && apk update \
  && apk upgrade --no-cache --available

# Install pipenv
RUN pip install --no-cache-dir pipenv==2026.6.2

# Create user and group
RUN addgroup -S apigroup && adduser -S apiuser -G apigroup -u 1051

# Set working directory
WORKDIR /home/coat-chatbot-frontend-v2

# Change ownership of the working directory
RUN chown -R apiuser:apigroup /home/coat-chatbot-frontend-v2

# Switch to non-root user
USER 1051

# Copy Pipfile and Pipfile.lock
COPY --chown=apiuser:apigroup Pipfile.api Pipfile.api.lock ./

# Environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PIPENV_PIPFILE=Pipfile.api

# Install dependencies without --system
RUN pipenv install --deploy --ignore-pipfile

# Copy application code
COPY --chown=apiuser:apigroup api api

# Expose port
EXPOSE 4567

# Healthcheck
HEALTHCHECK --interval=60s --timeout=30s CMD curl -I -XGET http://localhost:4567 || exit 1

# Use pipenv to run gunicorn
ENTRYPOINT ["pipenv", "run", "gunicorn", "--bind=0.0.0.0:4567", "api.run:api()"]
