version: "3.9"
services:
  app:
    build: .
    image: "coat-chatbot-frontend-v2"
    container_name: "coat-chatbot-frontend-v2"
    environment:
      # GitHub
      ADMIN_GITHUB_TOKEN: fake

      # Flask
      APP_SECRET_KEY: dev
      FLASK_DEBUG: true

      # Auth0
      AUTH_DISABLED: true

      # Sentry
      # SENTRY_DSN_KEY:
      SENTRY_ENV: local

      # App
      LOGGING_LEVEL: "DEBUG"
    ports:
      - "4567:4567"
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: "coat-chatbot-api"
    container_name: "coat-chatbot-api"
    environment:
      # Flask
      APP_SECRET_KEY: dev
      FLASK_DEBUG: true

      # App
      LOGGING_LEVEL: "DEBUG"
    ports:
      - "8080:4567"